### ISSUE TITLE
Cannot Get any of Data because the access being blocked by CORS Policy

### ISSUE THREAD

**Issue by ziunadev** [sooluh/kodepos#10]
Bang, barusan ane kena blok sama CORS policy

padahal sebelum"nya aman" aja

![image](https://user-images.githubusercontent.com/71458677/125197388-9bf63b80-e287-11eb-82ca-e10e5ee08715.png)

Kejadiannya pas banget setelah abang ngepush commit terakhir, sebelum abang push kodingan ane masih jalan

mohon bantuannya bang

nb: sebelumnya ane minta izin pake API abang

**Comment by sooluh** [comment]
halo mas putra,
untuk perubahan kode yang baru saja saya _commit_ memang terjadi beberapa kesalahan pada layanan _[serverless](https://en.wikipedia.org/wiki/Serverless_computing)_ yang saya pakai. saya akan mencoba cari tahu akar permasalahannya dan sesegera mungkin memperbaikinya.

untuk sementara mas putra boleh pakai atau mengalihkan sementara ke domain [kodepos.sdev.web.id](http://kodepos.sdev.web.id)
jika domain tersebut belum bisa diakses, itu karena ada proses [propagasi domain](https://www.google.com/search?q=propagasi+domain), masnya boleh tunggu paling lambat 24 jam.

maaf untuk kesalahan yang ada dan terimakasih sudah mau mengkonsumsi rest api yang saya buat 😅

**Comment by sooluh** [comment]
halo mas putra,
untuk perubahan kode yang baru saja saya _commit_ memang terjadi beberapa kesalahan pada layanan _[serverless](https://en.wikipedia.org/wiki/Serverless_computing)_ yang saya pakai. saya akan mencoba cari tahu akar permasalahannya dan sesegera mungkin memperbaikinya.

maaf untuk kesalahan yang ada dan terimakasih sudah mau mengkonsumsi rest api yang saya buat 😅

**Comment by sooluh** [comment]
halo mas putra,
untuk perubahan kode yang baru saja saya _commit_ memang terjadi beberapa kesalahan pada layanan _[serverless](https://en.wikipedia.org/wiki/Serverless_computing)_ yang saya pakai. saya akan mencoba cari tahu akar permasalahannya dan sesegera mungkin memperbaikinya.

untuk sementara masnya bisa pakai atau mengalihkan domainnya ke [kodepos-496sqx5d6-sooluh.vercel.app](https://kodepos-496sqx5d6-sooluh.vercel.app/)

maaf untuk kesalahan yang ada dan terimakasih sudah mau mengkonsumsi rest api yang saya buat 😅

**Comment by sooluh** [comment]
halo mas putra,
untuk perubahan kode yang baru saja saya _commit_ memang terjadi beberapa kesalahan pada layanan yang saya pakai. saya akan mencoba cari tahu akar permasalahannya dan sesegera mungkin memperbaikinya.

untuk sementara masnya bisa pakai atau mengalihkan domainnya ke [kodepos-496sqx5d6-sooluh.vercel.app](https://kodepos-496sqx5d6-sooluh.vercel.app/)

maaf untuk kesalahan yang ada dan terimakasih sudah mau mengkonsumsi rest api yang saya buat 😅

**Comment by ziunadev** [comment]
Sama-sama bang,

Ane juga mengucapkan terumakasih untuk respon dan solusinya

Issue ane tutup

**Comment by sooluh** [comment]
biarin open aja mas, sekalian nunggu fix 😁

**Comment by ziunadev** [comment]
> biarin open aja mas, sekalian nunggu fix 😁

Siap bang

**Comment by sooluh** [comment]
issue saya tutup kembali ya mas, masalah cors karna aplikasi gagal dideploy, jadi yang ditampilkan adalah "application error" dari layanan yang saya pakai.

issue terkait saya pindahkan ke issue baru, dan sementara masnya bisa pakai yang [kodepos.vercel.app](https://kodepos.vercel.app). untuk yang heroku nanti menyusul 😄

nb: maaf, untuk komentar masnya tadi kepencet 😢

**Comment by sooluh** [comment]
issue saya tutup kembali ya mas, masalah cors karena aplikasi gagal dideploy, jadi yang ditampilkan adalah pesan _internal server error_ dari layanan yang saya pakai.

issue terkait saya pindahkan ke issue baru, namun untuk deploy aplikasi ke vercel sudah fix, jadi masnya sudah bisa pakai domain yg [kodepos.vercel.app](https://kodepos.vercel.app), sementara untuk heroku masih coba saya perbaiki.

nb: maaf, untuk komentar masnya tadi kepencet hapus
