### ISSUE TITLE
Client Web App

### ISSUE THREAD

**Issue by dotslashf** [sooluh/kodepos#13]
i created web app using this repo, mind to add in README? thanks

https://kodepos-web.vercel.app/

**Comment by sooluh** [comment]
Impressive! I like it, thanks for the support, I've put it on `README.md`

**Comment by dotslashf** [comment]
Thank you so much, happy to help 👏  🚀

**Comment by sooluh** [comment]
If I may give a suggestion, it would be better if there was an action to copy the postcode on each search result card. @dotslashf

**Comment by dotslashf** [comment]
i see, i think that would be better instead of redirecting to google's search page, thanks for the suggestion, will work on it later! 👍
