### ISSUE TITLE
Add Parameters

### ISSUE THREAD

**Issue by sekedus** [sooluh/kodepos#18]
Please add more parameter, e.g. :

`https://kodepos.vercel.app/search/?city=cimahi&q=pasirkaliki`

`https://kodepos.vercel.app/search/?city=cimahi&subdistrict=cimahi%20utara&q=pasirkaliki`

`https://kodepos.vercel.app/search/?province=jawa%20barat&q=pasirkaliki`

**Comment by sooluh** [comment]
great idea, this is very possible, I will expand on it in the near future, thanks for the suggestion!

**Comment by sooluh** [comment]
released #32
